### ISSUE TITLE
Fix Screen Hanging

### ISSUE THREAD

**Issue by MrAgentBlaze** [depressed-pho/natural-mystic-shaders#16]
The Shader Hangs up my screen when loading Resources for global resources or world resource loading. Pls fix this immediantly
Android vesrion 6.0.1
Device: Samsung Galaxy S5

**Comment by depressed-pho** [comment]
Sorry, I have no clue why that happens. I have no Android devices to test my shaders. One of my friends tested it on Android and it worked on his device, so probably it's device dependent.
