### ISSUE TITLE
Good suggestion for help this shader.

### ISSUE THREAD

**Issue by StarlkYT** [depressed-pho/natural-mystic-shaders#18]
**There is good way to make this shader more popular.**

Add this shader in Github good idea, but add it to Discord would be better.
To make people talk with the author in real time, or send their suggestions 
And from this way this shaders will be better.

(Author) If do you see this idea good, please contact with me in Discord. I would help you a lot.
Discord ID: **! BITE - YT#0001**

**Comment by depressed-pho** [comment]
Thanks for the suggestion but I'm currently not interested in Discord, primarily due to it's high traffic which is way higher than what I can handle.
