### ISSUE TITLE
swimming

### ISSUE THREAD

**Issue by akaHelix** [depressed-pho/natural-mystic-shaders#39]
When swimming in water,
Screen becomes entirely black
But players anyway remain

**Comment by depressed-pho** [comment]
Can you post some screenshots?

**Comment by ivanevans28** [comment]
I had the same problem, only it happens rarely and I don’t have a screenshot.

**Comment by depressed-pho** [comment]
Only rarely? Hmm that sounds like a driver issue. I can't reproduce it at least.

**Comment by Oval** [comment]
This is not an issue with the shaders. It's reported at the Mojang bug tracker, as seen [here](https://bugs.mojang.com/browse/MCPE-32799).

**Comment by depressed-pho** [comment]
Oh nice. Thank you Oval!
