### ISSUE TITLE
Strange water texture?

### ISSUE THREAD

**Issue by ivanevans28** [depressed-pho/natural-mystic-shaders#41]
When the shaders pack is put on to global settings. It causes strange water glitches. (Could be related to screen turning black when swimming.) 
![4b16240a-93d7-4dd9-a325-69818847f149](https://user-images.githubusercontent.com/46284168/50717205-d6d9e180-1042-11e9-8fa8-4499157ea1d0.png)
Also freezes animation of water.

**Comment by depressed-pho** [comment]
Ah that's a known vanilla bug and can't fix with shaders. See https://bugs.mojang.com/browse/MCPE-39749
