### ISSUE TITLE
Make it not so orange.

### ISSUE THREAD

**Issue by gio1135** [depressed-pho/natural-mystic-shaders#60]
No idea why every shader makes everything so orange but I don't like it. I get that it's a torch light and all but it'd be so much better as white light in my opinion. If this won't go into the main release, can there at least be a variant, or you could show me where to change it?

**Comment by depressed-pho** [comment]
Yeah that's torchlight. You can change its color by editing ``shaders/glsl/natural-mystic-light.h``. It has a line like
```glsl
const vec3 torchlightColor = vec3(1.0, 0.66, 0.28);
```
and you can make it white by changing it to
```glsl
const vec3 torchlightColor = vec3(1.0);
```

**Comment by depressed-pho** [comment]
I hope someday we can have an in-game configuration screen, but for now I'm going to close this ticket.

**Comment by gio1135** [comment]
@depressed-pho Actually, I was about to exactly that but I didn't know if there were other factors which is the reason I came here in the first place. Thanks.
