### ISSUE TITLE
I don't know how else to contact you...

### ISSUE THREAD

**Issue by gio1135** [depressed-pho/natural-mystic-shaders#61]
I was just wanting to know if I could share the white light pack via MediaFire with some people on Reddit. Of course I won't take credit and also give credit.

I saw a post on r/Minecraft of a cave transformation and the shaders made it look really orange and I said so in the comments. People were agreeing and wanted a report back if I found anything with whiter light.

**Comment by MrAgentBlaze** [comment]
Contact him through discord @PHO#8773

**Comment by depressed-pho** [comment]
Yes you can. Natural Mystic Shaders is licensed under [CC0](https://creativecommons.org/share-your-work/public-domain/cc0/) which means I essentially abandoned the copyright to the maximum extent possible. You can even take credit and sell it to get money completely legitimately! I'm an anti-copyright activist and this is the very way how I act against it :D
