### ISSUE TITLE
Shaders dont work on Windows 10 1.9

### ISSUE THREAD

**Issue by ZoomIsEpic** [depressed-pho/natural-mystic-shaders#65]
when I set the shaders in my world it doesn't activate at all

**Comment by Ruben7173** [comment]
happends here as well

**Comment by gio1135** [comment]
I wish it did. No Windows 10 shaders are even good.

**Comment by kifodin2** [comment]
Here too

**Comment by gio1135** [comment]
Ok, yeah. It clearly only says iOS and Android so obviously it's known that if you tried it on Windows 10 edition that it's not gonna work. No need for confirming that it didn't work when you tried. It's practically spam at this point.

**Comment by depressed-pho** [comment]
Same as #25. Closing.
