### ISSUE TITLE
Crashes my minecraft

### ISSUE THREAD

**Issue by provsnoobgaming** [depressed-pho/natural-mystic-shaders#67]
I don't know why but everytime i load a shader pack it crashes my Minecraft I am using a galaxy j5 2016 android 6.0 it will just be stuck at loading screen a freeze the game

**Comment by kifodin2** [comment]
Crashes for me too while loading with Android 9.0 and a Kirin 980.

**Comment by gio1135** [comment]
Works for me on my Pixel 2 XL running Pie.

**Comment by depressed-pho** [comment]
Galaxy J5 2016 has a GPU Adreno 306, and Kirin 980 has Mali-G76MP10.
Sadly I can't debug those crash problems atm due to [MCPE-41076](https://bugs.mojang.com/browse/MCPE-41076). Closing the issue as a dupe of #50.
