### ISSUE TITLE
Orig shader src

### ISSUE THREAD

**Issue by Milky-Developer** [depressed-pho/natural-mystic-shaders#69]
Hi! This isn't much as a bug, but I unzipped the .apk file for mcpe 1.9.5, and there is quite a bit more source code! Some things that could potentially give access to the render pipeline, and fix many lighting entity bugs. The mediafire link of the extra shader source code from mcpe is here: (on this zip)

http://www.mediafire.com/file/eplyfacwmpt75l7/ShadersSRC.zip/file

**Comment by depressed-pho** [comment]
Thanks, but I too have access to those files :D
