### ISSUE TITLE
World doesnt load when using the mod.

### ISSUE THREAD

**Issue by karte34123** [depressed-pho/natural-mystic-shaders#71]
I dont know what causes this issue 
Here's a pic of the issue 
![Screenshot_20190603-123945](https://user-images.githubusercontent.com/51336018/58822524-5cb38600-85fd-11e9-9b01-c9413e46ddef.jpg)

Im currently using a huawei p20 lite

**Comment by gio1135** [comment]
Are the animals not enough for you?

**Comment by xxRaiyanxxYT** [comment]
Same

**Comment by depressed-pho** [comment]
Closing this one because it's the same as #73. Your world was surely loaded (because the animals are there), but the game failed to run my terrain shader *for a reason unknown to me*.
