### ISSUE TITLE
Strange leaf behavior in snowy/cold biomes

### ISSUE THREAD

**Issue by Nickonizer** [depressed-pho/natural-mystic-shaders#76]
I was in a snow biome and the leaves were glitching out then in a non snow biome next to it they were fine this effects all leaf types not just spruce.

**Comment by gio1135** [comment]
> I was in a snow biome and the leaves were glitching out then in a non snow biome next to it they were fine this effects all leaf types not just spruce.

;-;

**Comment by depressed-pho** [comment]
That happens when my terrain shader misrecognizes leaves as water. It happened once on my device, and I fixed it at that time. I hope it no longer happens.
