### ISSUE TITLE
Windows 10

### ISSUE THREAD

**Issue by PiSaucer** [depressed-pho/natural-mystic-shaders#82]
It doesn't work with windows 10. When Install it, it will load with no changes. On my android phone, it runs fine. Do you have any ideas why?

**Comment by gio1135** [comment]
[oh fr](https://github.com/depressed-pho/natural-mystic-shaders#supported-platforms)

**Comment by KindaWeirdAsian** [comment]
Same

**Comment by depressed-pho** [comment]
Same as #25. I can't support Win10 atm.
