### ISSUE TITLE
TIME

### ISSUE THREAD

**Issue by YamaR1n** [depressed-pho/natural-mystic-shaders#87]
Natural Mystic では TIME を使用して波や揺れの処理を行っているようですが、それは現在ではサポートされておらず、すべての端末できちんと動作するのかは怪しいです。同じくサポートを受けられなくなった変数として VIEW_POSがあります。それは昔、プレイヤーの視線の位置情報だったようですがゲームのバージョン1.2 あたりから (おそらく互換性の問題で) すべてのコンポーネントの値が０になり、削除されました。TIMEの話に戻るとそれよりも比較的最近追加された TOTAL_REAL_WORLD_TIME を使用するのが好ましいです。GL_FRAGMENT_PRECISION_HIGH による精度の切り替え (#86) と併用して uniform すれば、より多くの種類の端末で確実に動作するでしょう。

**Comment by depressed-pho** [comment]
修正しました。ありがとうございます。
